<?php use App\Services\StorageService; $previous = (float) $bill['running_balance'] - (float) $bill['amount']; ?>
<div class="mx-auto max-w-md">
  <div class="rounded-3xl bg-white p-6 text-center shadow-sm ring-1 ring-slate-100">
    <div class="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-green-100 text-green-700"><svg class="h-7 w-7" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="m4.5 12.75 6 6 9-13.5"/></svg></div>
    <h1 class="mt-3 text-xl font-bold text-slate-900">Bill Added</h1><p class="text-sm text-slate-500"><?= e($bill['customer_name']) ?></p>
    <dl class="mt-5 space-y-3 border-y border-slate-100 py-4 text-sm"><div class="flex justify-between"><dt class="text-slate-500">Bill number</dt><dd class="font-bold"><?= e($bill['bill_number']) ?></dd></div><div class="flex justify-between"><dt class="text-slate-500">Bill date</dt><dd class="font-bold"><?= e(date('j M Y', strtotime($bill['transaction_date']))) ?></dd></div><div class="flex justify-between"><dt class="text-slate-500">Previous outstanding</dt><dd><?= money($previous) ?></dd></div><div class="flex justify-between"><dt class="text-slate-500">New bill</dt><dd class="font-bold text-amber-600">+ <?= money($bill['amount']) ?></dd></div><div class="flex justify-between text-base"><dt class="font-bold">New outstanding</dt><dd class="font-bold text-brand-700"><?= money($bill['running_balance']) ?></dd></div></dl>
    <?php if (!empty($bill['image_path'])): ?><a href="<?= e(StorageService::url($bill['image_path'])) ?>" target="_blank" class="mt-4 inline-flex text-sm font-bold text-brand-600">View bill image</a><?php endif; ?>
  </div>
  <div class="mt-4 grid gap-2"><a href="<?= e(url('bills/' . $bill['id'] . '/edit')) ?>" class="btn btn-outline btn-full"><?= ui_icon('pencil', 'h-4 w-4') ?> Edit Bill</a><a href="<?= e(url('customers/' . $bill['customer_id'])) ?>" class="btn btn-primary btn-full">View Customer Ledger</a><a href="<?= e(url('customers/' . $bill['customer_id'] . '/bill')) ?>" class="btn btn-outline btn-full">Add Another Bill</a><a href="<?= e(url('')) ?>" class="py-2 text-center text-sm font-semibold text-slate-500">Done</a></div>
</div>
